In [132]:
#Question One

In [80]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

u'0.24.2'

In [134]:
#Question 2

In [133]:
Csv1 = pd.read_csv("Csv1.csv")

In [61]:
Csv2 = pd.read_csv("Csv2.csv")

In [8]:
len(Csv1)

119

In [10]:
len(Csv2)

115

In [135]:
#Question 3

In [299]:
Csv3 = pd.merge(Csv1, Csv2, left_index=True, right_index=True)
Csv3

,Address.City_x,ID_x,LocationMilestones.LastRemodelDate,LocationMilestones.OpenDate,Name_x,Store.StoreDistrictID,TimeZone.TimeZoneCode,PhoneNumber,Address.City_y,ID_y,Name_y,FaxNumber,BeginTime.MF,ThruTime.MF,IsOpen.Sat,IsOpen.Sun
0,Oxford,2153,NaN,2006-07-19T12:00:00,Oxford,340,CST,(256) 231-2900,Oxford,2153,Oxford,(256) 231-2910,08:00:00,22:00:00,True,False
1,Opelika,1499,NaN,2005-07-20T12:00:00,Opelika,340,CST,(334) 705-0152,Opelika,1499,Opelika,(334) 363-3235,08:00:00,22:00:00,False,True
2,Carrollton,1073,NaN,1997-07-23T12:00:00,Carrollton,336,EST,(770) 838-9221,Carrollton,1073,Carrollton,(678) 664-3234,08:00:00,22:00:00,True,True
3,Newnan,1223,2013-06-27T12:00:00,1999-10-06T12:00:00,Newnan,336,EST,(770) 502-0294,Newnan,1223,Newnan,(678) 621-6321,08:00:00,22:00:00,True,False
4,Columbus,1179,2004-10-17T12:00:00,1999-03-03T12:00:00,Columbus,340,EST,(706) 321-0831,Columbus,1179,Columbus,(706) 225-5604,08:00:00,23:00:00,True,True
5,Peachtree City,2129,2013-10-10T12:00:00,2006-07-19T12:00:00,Peachtree City,336,EST,(770) 282-2165,Peachtree City,2129,Peachtree City,(678) 734-3839,08:00:00,22:00:00,True,False
6,Montgomery,1825,2014-04-03T12:00:00,2003-10-08T12:00:00,Montgomery,340,CST,(334) 356-6265,Montgomery,1825,Montgomery,(334) 523-9794,08:00:00,22:00:00,True,True
7,Douglasville,1172,NaN,1998-10-07T12:00:00,Douglasville,336,EST,(770) 947-5303,Douglasville,1172,Douglasville,(770) 250-4101,08:00:00,22:00:00,False,True
8,Prattville,2274,NaN,2007-07-25T12:00:00,Prattville,340,CST,(334) 290-6000,Prattville,2274,Prattville,(334) 290-6010,08:00:00,22:00:00,True,True
9,Birmingham,1772,NaN,2000-10-04T12:00:00,Birmingham 280 Corridor,340,CST,(205) 408-7687,Birmingham,1772,Birmingham 280 Corridor,(205) 578-5170,08:00:00,23:00:00,True,True
10,Fayetteville,778,2007-10-18T12:00:00,1995-10-04T12:00:00,Fayetteville,336,EST,(770) 719-9766,Fayetteville,778,Fayetteville,(678) 734-9930,08:00:00,22:00:00,True,True
11,Birmingham,1773,NaN,2000-10-04T12:00:00,Trussville,340,CST,(205) 655-6950,Birmingham,1773,Trussville,(205) 661-8157,08:00:00,22:00:00,True,False
12,Hiram,1400,NaN,2002-03-06T12:00:00,Hiram,336,EST,(678) 567-0142,Hiram,1400,Hiram,(770) 250-4784,08:00:00,23:00:00,True,True
13,Alabaster,2276,NaN,2007-07-25T12:00:00,Alabaster,340,CST,(205) 564-2608,Alabaster,2276,Alabaster,(205) 564-2853,08:00:00,22:00:00,True,True
14,East Point,1546,2012-06-21T12:00:00,2003-07-23T12:00:00,East Point,336,EST,(404) 267-0063,East Point,1546,East Point,(404) 720-5338,08:00:00,23:00:00,True,True
15,Homewood,2796,NaN,2013-03-06T12:00:00,Homewood,340,CST,(205) 994-7531,Homewood,2796,Homewood,(205) 994-7541,08:00:00,23:00:00,True,False
16,Austell,1164,2004-08-08T12:00:00,1999-03-03T12:00:00,Austell,336,EST,(678) 945-4550,Austell,1164,Austell,(770) 250-4829,08:00:00,22:00:00,True,False
17,Birmingham,2503,NaN,2009-10-07T12:00:00,Hoover West,340,CST,(205) 747-1654,Birmingham,2503,Hoover West,(205) 747-1664,08:00:00,23:00:00,True,False
18,Marietta,1165,2013-06-27T12:00:00,1998-10-07T12:00:00,West Marietta,334,EST,(770) 792-7933,Marietta,1165,West Marietta,(770) 250-7030,08:00:00,22:00:00,True,True
19,Fultondale,2355,NaN,2007-10-10T12:00:00,Fultondale,340,CST,(205) 453-6032,Fultondale,2355,Fultondale,(205) 578-5030,08:00:00,22:00:00,True,True
20,Acworth,2091,NaN,2006-07-19T12:00:00,Acworth,334,EST,(678) 202-0996,Acworth,2091,Acworth,(770) 250-4971,08:00:00,22:00:00,True,True
21,Mcdonough,1461,NaN,2002-07-24T12:00:00,McDonough,346,EST,(678) 583-2184,Mcdonough,1461,McDonough,(678) 734-3914,08:00:00,23:00:00,True,True
22,Atlanta,2137,2012-03-22T12:00:00,2007-10-10T12:00:00,Atlanta Midtown,336,EST,(678) 954-4265,Atlanta,2137,Atlanta Midtown,(678) 954-4275,08:00:00,23:00:00,False,True
23,Smyrna,373,2012-03-22T12:00:00,1989-04-26T12:00:00,Smyrna,334,EST,(770) 952-2241,Smyrna,373,Smyrna,(770) 250-7501,08:00:00,23:00:00,True,False
24,Atlanta,1964,2012-03-22T12:00:00,2005-03-02T12:00:00,Atlanta Edgewood,336,EST,(404) 260-0200,Atlanta,1964,Atlanta Edgewood,(404) 682-7559,07:00:00,23:00:00,True,False
25,Bessemer,2375,NaN,2008-07-23T12:00:00,Bessemer,340,CST,(205) 565-3760,Bessemer,2375,Bessemer,(205) 565-3770,08:00:00,22:00:00,True,True
26,Kennesaw,981,2012-06-21T12:00:00,1995-07-19T12:00:00,Cobb,334,EST,(770) 425-6895,Kennesaw,981,Cobb,(770) 250-7010,08:00:00,23:00:00,True,True
27,Atlanta,2171,2012-06-21T12:00:00,2006-10-04T12:00:00,Buckhead South,335,EST,(404) 720-1081,Atlanta,2171,Buckhead South,(404) 682-2140,08:00:00,23:00:00,True,True
28,Cartersville,969,2017-03-30T12:00:00,1995-10-04T12:00:00,Cartersville,334,EST,(770) 387-9595,Cartersville,969,Cartersville,(678) 719-3154,08:00:00,22:00:00,True,True
29,Atlanta,1197,2012-06-21T12:00:00,1999-07-21T12:00:00,Buckhead,335,EST,(404) 237-9494,Atlanta,1197,Buckhead,(404) 720-7752,08:00:00,23:00:00,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Franklin,695,2012-06-21T12:00:00,1992-03-11T12:00:00,Cool Springs,369,CST,(615) 771-2093,Franklin,695,Cool Springs,(615) 472-9691,08:00:00,23:00:00,True,True
86,Knoxville,151,2014-04-03T12:00:00,1981-07-22T12:00:00,Knoxville West,351,EST,(865) 693-2203,Knoxville,151,Knoxville West,(865) 291-4819,08:00:00,23:00:00,True,False
87,Brentwood,1983,2012-06-21T12:00:00,2005-07-20T12:00:00,Brentwood,369,CST,(615) 238-0126,Brentwood,1983,Brentwood,(615) 208-8402,08:00:00,23:00:00,True,True
88,Mount Juliet,2126,2012-06-21T12:00:00,2006-03-01T12:00:00,Mt Juliet,333,CST,(615) 773-2800,Mount Juliet,2126,Mt Juliet,NaN,08:00:00,22:00:00,True,True
89,Pensacola,2445,NaN,2009-03-04T12:00:00,Pensacola West,359,CST,(850) 454-3000,Pensacola,2445,Pensacola West,(850) 454-3010,08:00:00,22:00:00,True,True
90,Knoxville,795,2017-04-13T12:00:00,1996-03-06T12:00:00,Knoxville NW,351,EST,(865) 947-7636,Knoxville,795,Knoxville NW,NaN,08:00:00,22:00:00,True,True
91,Simpsonville,1870,2012-10-11T12:00:00,2004-03-03T12:00:00,Simpsonville,337,EST,(864) 963-7251,Simpsonville,1870,Simpsonville,(864) 757-3201,08:00:00,22:00:00,True,True
92,Nashville,1059,2010-10-14T12:00:00,1997-03-05T12:00:00,Nashville East,333,CST,(615) 889-4734,Nashville,1059,Nashville East,(615) 925-3840,08:00:00,22:00:00,True,False
93,Nashville,146,2012-03-22T12:00:00,1981-07-22T12:00:00,White Bridge,369,CST,(615) 352-8461,Nashville,146,White Bridge,(615) 970-3683,08:00:00,23:00:00,True,True
94,Greenville,1182,2012-06-21T12:00:00,1999-03-03T12:00:00,Greenville,337,EST,(864) 286-3689,Greenville,1182,Greenville,(864) 558-2543,08:00:00,23:00:00,True,True
95,Nashville,2240,2012-03-22T12:00:00,2007-03-07T12:00:00,Nashville West,369,CST,(615) 238-0112,Nashville,2240,Nashville West,(615) 970-3895,08:00:00,23:00:00,True,True
96,Daphne,1274,2018-04-13T12:00:00,2000-07-19T12:00:00,Daphne,359,CST,(251) 621-3540,Daphne,1274,Daphne,(251) 287-9804,08:00:00,22:00:00,True,True
97,Knoxville,2057,2014-04-03T12:00:00,2006-07-19T12:00:00,Knoxville North,351,EST,(865) 291-0086,Knoxville,2057,Knoxville North,(865) 291-4757,08:00:00,22:00:00,True,True
98,Aiken,1310,2006-05-12T12:00:00,2000-10-04T12:00:00,Aiken,337,EST,(803) 644-2721,Aiken,1310,Aiken,(803) 295-5701,08:00:00,22:00:00,True,True
99,Mobile,797,2003-08-12T12:00:00,1996-07-24T12:00:00,Bel-Air,359,CST,(251) 471-9760,Mobile,797,Bel-Air,(251) 287-9863,08:00:00,22:00:00,True,True
100,Taylors,1937,2012-03-22T12:00:00,2004-10-06T12:00:00,Greer,337,EST,(864) 801-8128,Taylors,1937,Greer,(864) 416-5786,08:00:00,23:00:00,True,False
101,Madison,144,2007-03-23T12:00:00,1981-02-24T12:00:00,Rivergate,333,CST,(615) 859-5260,Madison,144,Rivergate,(615) 756-3261,08:00:00,22:00:00,True,True
102,Hendersonville,1511,2012-10-11T12:00:00,2003-03-05T12:00:00,Hendersonville,333,CST,(615) 826-6895,Hendersonville,1511,Hendersonville,(615) 431-3581,08:00:00,22:00:00,True,True
103,Mobile,1376,NaN,2002-03-06T12:00:00,Mobile West,359,CST,(251) 607-0265,Mobile,1376,Mobile West,(251) 287-9784,08:00:00,23:00:00,True,True
104,Gulf Shores,2154,2012-06-21T12:00:00,2006-07-19T12:00:00,Gulf Shores,359,CST,(251) 967-7001,Gulf Shores,2154,Gulf Shores,NaN,08:00:00,22:00:00,True,True
105,Arden,2011,2012-06-21T12:00:00,2005-07-20T12:00:00,Asheville South,362,EST,(828) 681-0341,Arden,2011,Asheville South,(828) 974-3269,08:00:00,22:00:00,True,False
106,Spartanburg,1349,2012-06-21T12:00:00,2001-07-25T12:00:00,Spartanburg,337,EST,(864) 574-1211,Spartanburg,1349,Spartanburg,(864) 345-6000,08:00:00,22:00:00,True,True
107,Asheville,1807,2012-03-22T12:00:00,2003-07-23T12:00:00,Asheville,362,EST,(828) 298-1262,Asheville,1807,Asheville,(828) 333-9991,08:00:00,23:00:00,True,True
108,Palm Desert,940,2011-06-02T12:00:00,1995-03-08T12:00:00,Palm Desert,205,PST,(760) 341-9307,Jackson,921,Jackson,(731) 256-3707,08:00:00,22:00:00,False,True
109,Cathedral City,307,2011-10-06T12:00:00,1987-07-22T12:00:00,Palm Springs,205,PST,(760) 321-7425,Collierville,1907,Collierville,(901) 471-2051,08:00:00,22:00:00,True,True
110,Apple Valley,2260,NaN,2007-07-25T12:00:00,Apple Valley North,248,PST,(760) 240-7654,Germantown,682,Germantown,(901) 251-4411,08:00:00,22:00:00,True,True
111,Apple Valley,939,2011-10-06T12:00:00,1994-10-05T12:00:00,Apple Valley,248,PST,(760) 247-4111,Cordova,1844,Cordova,(901) 251-0368,08:00:00,23:00:00,True,False
112,Hesperia,2468,NaN,2008-10-08T12:00:00,Hesperia,248,PST,(760) 949-3062,Olive Branch,2442,Olive Branch West,(662) 892-3041,08:00:00,22:00:00,True,True
113,Grand Junction,93,2014-10-12T12:00:00,1980-10-28T12:00:00,Grand Junction,179,MST,(970) 245-8056,Memphis,1030,Memphis NE,(901) 251-5411,08:00:00,23:00:00,True,False
114,Montrose,2343,NaN,2007-10-10T12:00:00,Montrose,179,MST,(970) 497-8980,Memphis,2474,Memphis East,(901) 261-5089,08:00:00,23:00:00,True,False

In [136]:
#Question 4

In [184]:
Csv3.shape

(115, 16)

In [186]:
Csv3.dtypes

Address.City_x                        object
ID_x                                   int64
LocationMilestones.LastRemodelDate    object
LocationMilestones.OpenDate           object
Name_x                                object
Store.StoreDistrictID                  int64
TimeZone.TimeZoneCode                 object
PhoneNumber                           object
Address.City_y                        object
ID_y                                   int64
Name_y                                object
FaxNumber                             object
BeginTime.MF                          object
ThruTime.MF                           object
IsOpen.Sat                              bool
IsOpen.Sun                              bool
dtype: object

In [294]:
Csv3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 115 entries, 0 to 114
Data columns (total 16 columns):
Address.City_x                        115 non-null object
ID_x                                  115 non-null int64
LocationMilestones.LastRemodelDate    77 non-null object
LocationMilestones.OpenDate           115 non-null object
Name_x                                115 non-null object
Store.StoreDistrictID                 115 non-null int64
TimeZone.TimeZoneCode                 115 non-null object
PhoneNumber                           115 non-null object
Address.City_y                        115 non-null object
ID_y                                  115 non-null int64
Name_y                                115 non-null object
FaxNumber                             110 non-null object
BeginTime.MF                          115 non-null object
ThruTime.MF                           115 non-null object
IsOpen.Sat                            115 non-null bool
IsOpen.Sun                            115 non-null bool
dtypes: bool(2), int64(3), object(11)
memory usage: 13.7+ KB

In [295]:
Csv3.values

array([['Oxford', 2153L, nan, ..., '22:00:00', True, False],
       ['Opelika', 1499L, nan, ..., '22:00:00', False, True],
       ['Carrollton', 1073L, nan, ..., '22:00:00', True, True],
       ...,
       ['Hesperia', 2468L, nan, ..., '22:00:00', True, True],
       ['Grand Junction', 93L, '2014-10-12T12:00:00', ..., '23:00:00',
        True, False],
       ['Montrose', 2343L, nan, ..., '23:00:00', True, False]],
      dtype=object)

In [306]:
List(Csv3.values)

TypeError: 'list' object is not callable

In [137]:
#Question 5

In [227]:
Csv3.rename(columns = {"Name" :"Store Name"}, inplace = True)
Csv3

,Address.City_x,ID_x,LocationMilestones.LastRemodelDate,LocationMilestones.OpenDate,Name_x,Store.StoreDistrictID,TimeZone.TimeZoneCode,PhoneNumber,Address.City_y,ID_y,Name_y,FaxNumber,BeginTime.MF,ThruTime.MF,IsOpen.Sat,IsOpen.Sun
0,Oxford,2153,NaN,2006-07-19T12:00:00,Oxford,340,CST,(256) 231-2900,Oxford,2153,Oxford,(256) 231-2910,08:00:00,22:00:00,True,False
1,Opelika,1499,NaN,2005-07-20T12:00:00,Opelika,340,CST,(334) 705-0152,Opelika,1499,Opelika,(334) 363-3235,08:00:00,22:00:00,False,True
2,Carrollton,1073,NaN,1997-07-23T12:00:00,Carrollton,336,EST,(770) 838-9221,Carrollton,1073,Carrollton,(678) 664-3234,08:00:00,22:00:00,True,True
3,Newnan,1223,2013-06-27T12:00:00,1999-10-06T12:00:00,Newnan,336,EST,(770) 502-0294,Newnan,1223,Newnan,(678) 621-6321,08:00:00,22:00:00,True,False
4,Columbus,1179,2004-10-17T12:00:00,1999-03-03T12:00:00,Columbus,340,EST,(706) 321-0831,Columbus,1179,Columbus,(706) 225-5604,08:00:00,23:00:00,True,True
5,Peachtree City,2129,2013-10-10T12:00:00,2006-07-19T12:00:00,Peachtree City,336,EST,(770) 282-2165,Peachtree City,2129,Peachtree City,(678) 734-3839,08:00:00,22:00:00,True,False
6,Montgomery,1825,2014-04-03T12:00:00,2003-10-08T12:00:00,Montgomery,340,CST,(334) 356-6265,Montgomery,1825,Montgomery,(334) 523-9794,08:00:00,22:00:00,True,True
7,Douglasville,1172,NaN,1998-10-07T12:00:00,Douglasville,336,EST,(770) 947-5303,Douglasville,1172,Douglasville,(770) 250-4101,08:00:00,22:00:00,False,True
8,Prattville,2274,NaN,2007-07-25T12:00:00,Prattville,340,CST,(334) 290-6000,Prattville,2274,Prattville,(334) 290-6010,08:00:00,22:00:00,True,True
9,Birmingham,1772,NaN,2000-10-04T12:00:00,Birmingham 280 Corridor,340,CST,(205) 408-7687,Birmingham,1772,Birmingham 280 Corridor,(205) 578-5170,08:00:00,23:00:00,True,True
10,Fayetteville,778,2007-10-18T12:00:00,1995-10-04T12:00:00,Fayetteville,336,EST,(770) 719-9766,Fayetteville,778,Fayetteville,(678) 734-9930,08:00:00,22:00:00,True,True
11,Birmingham,1773,NaN,2000-10-04T12:00:00,Trussville,340,CST,(205) 655-6950,Birmingham,1773,Trussville,(205) 661-8157,08:00:00,22:00:00,True,False
12,Hiram,1400,NaN,2002-03-06T12:00:00,Hiram,336,EST,(678) 567-0142,Hiram,1400,Hiram,(770) 250-4784,08:00:00,23:00:00,True,True
13,Alabaster,2276,NaN,2007-07-25T12:00:00,Alabaster,340,CST,(205) 564-2608,Alabaster,2276,Alabaster,(205) 564-2853,08:00:00,22:00:00,True,True
14,East Point,1546,2012-06-21T12:00:00,2003-07-23T12:00:00,East Point,336,EST,(404) 267-0063,East Point,1546,East Point,(404) 720-5338,08:00:00,23:00:00,True,True
15,Homewood,2796,NaN,2013-03-06T12:00:00,Homewood,340,CST,(205) 994-7531,Homewood,2796,Homewood,(205) 994-7541,08:00:00,23:00:00,True,False
16,Austell,1164,2004-08-08T12:00:00,1999-03-03T12:00:00,Austell,336,EST,(678) 945-4550,Austell,1164,Austell,(770) 250-4829,08:00:00,22:00:00,True,False
17,Birmingham,2503,NaN,2009-10-07T12:00:00,Hoover West,340,CST,(205) 747-1654,Birmingham,2503,Hoover West,(205) 747-1664,08:00:00,23:00:00,True,False
18,Marietta,1165,2013-06-27T12:00:00,1998-10-07T12:00:00,West Marietta,334,EST,(770) 792-7933,Marietta,1165,West Marietta,(770) 250-7030,08:00:00,22:00:00,True,True
19,Fultondale,2355,NaN,2007-10-10T12:00:00,Fultondale,340,CST,(205) 453-6032,Fultondale,2355,Fultondale,(205) 578-5030,08:00:00,22:00:00,True,True
20,Acworth,2091,NaN,2006-07-19T12:00:00,Acworth,334,EST,(678) 202-0996,Acworth,2091,Acworth,(770) 250-4971,08:00:00,22:00:00,True,True
21,Mcdonough,1461,NaN,2002-07-24T12:00:00,McDonough,346,EST,(678) 583-2184,Mcdonough,1461,McDonough,(678) 734-3914,08:00:00,23:00:00,True,True
22,Atlanta,2137,2012-03-22T12:00:00,2007-10-10T12:00:00,Atlanta Midtown,336,EST,(678) 954-4265,Atlanta,2137,Atlanta Midtown,(678) 954-4275,08:00:00,23:00:00,False,True
23,Smyrna,373,2012-03-22T12:00:00,1989-04-26T12:00:00,Smyrna,334,EST,(770) 952-2241,Smyrna,373,Smyrna,(770) 250-7501,08:00:00,23:00:00,True,False
24,Atlanta,1964,2012-03-22T12:00:00,2005-03-02T12:00:00,Atlanta Edgewood,336,EST,(404) 260-0200,Atlanta,1964,Atlanta Edgewood,(404) 682-7559,07:00:00,23:00:00,True,False
25,Bessemer,2375,NaN,2008-07-23T12:00:00,Bessemer,340,CST,(205) 565-3760,Bessemer,2375,Bessemer,(205) 565-3770,08:00:00,22:00:00,True,True
26,Kennesaw,981,2012-06-21T12:00:00,1995-07-19T12:00:00,Cobb,334,EST,(770) 425-6895,Kennesaw,981,Cobb,(770) 250-7010,08:00:00,23:00:00,True,True
27,Atlanta,2171,2012-06-21T12:00:00,2006-10-04T12:00:00,Buckhead South,335,EST,(404) 720-1081,Atlanta,2171,Buckhead South,(404) 682-2140,08:00:00,23:00:00,True,True
28,Cartersville,969,2017-03-30T12:00:00,1995-10-04T12:00:00,Cartersville,334,EST,(770) 387-9595,Cartersville,969,Cartersville,(678) 719-3154,08:00:00,22:00:00,True,True
29,Atlanta,1197,2012-06-21T12:00:00,1999-07-21T12:00:00,Buckhead,335,EST,(404) 237-9494,Atlanta,1197,Buckhead,(404) 720-7752,08:00:00,23:00:00,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Franklin,695,2012-06-21T12:00:00,1992-03-11T12:00:00,Cool Springs,369,CST,(615) 771-2093,Franklin,695,Cool Springs,(615) 472-9691,08:00:00,23:00:00,True,True
86,Knoxville,151,2014-04-03T12:00:00,1981-07-22T12:00:00,Knoxville West,351,EST,(865) 693-2203,Knoxville,151,Knoxville West,(865) 291-4819,08:00:00,23:00:00,True,False
87,Brentwood,1983,2012-06-21T12:00:00,2005-07-20T12:00:00,Brentwood,369,CST,(615) 238-0126,Brentwood,1983,Brentwood,(615) 208-8402,08:00:00,23:00:00,True,True
88,Mount Juliet,2126,2012-06-21T12:00:00,2006-03-01T12:00:00,Mt Juliet,333,CST,(615) 773-2800,Mount Juliet,2126,Mt Juliet,NaN,08:00:00,22:00:00,True,True
89,Pensacola,2445,NaN,2009-03-04T12:00:00,Pensacola West,359,CST,(850) 454-3000,Pensacola,2445,Pensacola West,(850) 454-3010,08:00:00,22:00:00,True,True
90,Knoxville,795,2017-04-13T12:00:00,1996-03-06T12:00:00,Knoxville NW,351,EST,(865) 947-7636,Knoxville,795,Knoxville NW,NaN,08:00:00,22:00:00,True,True
91,Simpsonville,1870,2012-10-11T12:00:00,2004-03-03T12:00:00,Simpsonville,337,EST,(864) 963-7251,Simpsonville,1870,Simpsonville,(864) 757-3201,08:00:00,22:00:00,True,True
92,Nashville,1059,2010-10-14T12:00:00,1997-03-05T12:00:00,Nashville East,333,CST,(615) 889-4734,Nashville,1059,Nashville East,(615) 925-3840,08:00:00,22:00:00,True,False
93,Nashville,146,2012-03-22T12:00:00,1981-07-22T12:00:00,White Bridge,369,CST,(615) 352-8461,Nashville,146,White Bridge,(615) 970-3683,08:00:00,23:00:00,True,True
94,Greenville,1182,2012-06-21T12:00:00,1999-03-03T12:00:00,Greenville,337,EST,(864) 286-3689,Greenville,1182,Greenville,(864) 558-2543,08:00:00,23:00:00,True,True
95,Nashville,2240,2012-03-22T12:00:00,2007-03-07T12:00:00,Nashville West,369,CST,(615) 238-0112,Nashville,2240,Nashville West,(615) 970-3895,08:00:00,23:00:00,True,True
96,Daphne,1274,2018-04-13T12:00:00,2000-07-19T12:00:00,Daphne,359,CST,(251) 621-3540,Daphne,1274,Daphne,(251) 287-9804,08:00:00,22:00:00,True,True
97,Knoxville,2057,2014-04-03T12:00:00,2006-07-19T12:00:00,Knoxville North,351,EST,(865) 291-0086,Knoxville,2057,Knoxville North,(865) 291-4757,08:00:00,22:00:00,True,True
98,Aiken,1310,2006-05-12T12:00:00,2000-10-04T12:00:00,Aiken,337,EST,(803) 644-2721,Aiken,1310,Aiken,(803) 295-5701,08:00:00,22:00:00,True,True
99,Mobile,797,2003-08-12T12:00:00,1996-07-24T12:00:00,Bel-Air,359,CST,(251) 471-9760,Mobile,797,Bel-Air,(251) 287-9863,08:00:00,22:00:00,True,True
100,Taylors,1937,2012-03-22T12:00:00,2004-10-06T12:00:00,Greer,337,EST,(864) 801-8128,Taylors,1937,Greer,(864) 416-5786,08:00:00,23:00:00,True,False
101,Madison,144,2007-03-23T12:00:00,1981-02-24T12:00:00,Rivergate,333,CST,(615) 859-5260,Madison,144,Rivergate,(615) 756-3261,08:00:00,22:00:00,True,True
102,Hendersonville,1511,2012-10-11T12:00:00,2003-03-05T12:00:00,Hendersonville,333,CST,(615) 826-6895,Hendersonville,1511,Hendersonville,(615) 431-3581,08:00:00,22:00:00,True,True
103,Mobile,1376,NaN,2002-03-06T12:00:00,Mobile West,359,CST,(251) 607-0265,Mobile,1376,Mobile West,(251) 287-9784,08:00:00,23:00:00,True,True
104,Gulf Shores,2154,2012-06-21T12:00:00,2006-07-19T12:00:00,Gulf Shores,359,CST,(251) 967-7001,Gulf Shores,2154,Gulf Shores,NaN,08:00:00,22:00:00,True,True
105,Arden,2011,2012-06-21T12:00:00,2005-07-20T12:00:00,Asheville South,362,EST,(828) 681-0341,Arden,2011,Asheville South,(828) 974-3269,08:00:00,22:00:00,True,False
106,Spartanburg,1349,2012-06-21T12:00:00,2001-07-25T12:00:00,Spartanburg,337,EST,(864) 574-1211,Spartanburg,1349,Spartanburg,(864) 345-6000,08:00:00,22:00:00,True,True
107,Asheville,1807,2012-03-22T12:00:00,2003-07-23T12:00:00,Asheville,362,EST,(828) 298-1262,Asheville,1807,Asheville,(828) 333-9991,08:00:00,23:00:00,True,True
108,Palm Desert,940,2011-06-02T12:00:00,1995-03-08T12:00:00,Palm Desert,205,PST,(760) 341-9307,Jackson,921,Jackson,(731) 256-3707,08:00:00,22:00:00,False,True
109,Cathedral City,307,2011-10-06T12:00:00,1987-07-22T12:00:00,Palm Springs,205,PST,(760) 321-7425,Collierville,1907,Collierville,(901) 471-2051,08:00:00,22:00:00,True,True
110,Apple Valley,2260,NaN,2007-07-25T12:00:00,Apple Valley North,248,PST,(760) 240-7654,Germantown,682,Germantown,(901) 251-4411,08:00:00,22:00:00,True,True
111,Apple Valley,939,2011-10-06T12:00:00,1994-10-05T12:00:00,Apple Valley,248,PST,(760) 247-4111,Cordova,1844,Cordova,(901) 251-0368,08:00:00,23:00:00,True,False
112,Hesperia,2468,NaN,2008-10-08T12:00:00,Hesperia,248,PST,(760) 949-3062,Olive Branch,2442,Olive Branch West,(662) 892-3041,08:00:00,22:00:00,True,True
113,Grand Junction,93,2014-10-12T12:00:00,1980-10-28T12:00:00,Grand Junction,179,MST,(970) 245-8056,Memphis,1030,Memphis NE,(901) 251-5411,08:00:00,23:00:00,True,False
114,Montrose,2343,NaN,2007-10-10T12:00:00,Montrose,179,MST,(970) 497-8980,Memphis,2474,Memphis East,(901) 261-5089,08:00:00,23:00:00,True,False

In [138]:
#Question 6

In [69]:
missing_values = ["n/a", "na", "--"]
df = pd.read_csv("Csv1.csv", na_values = missing_values)

In [176]:
#print df.isnull().sum()

In [71]:
missing_values = ["n/a", "na", "--"]
df = pd.read_csv("Csv2.csv", na_values = missing_values)

In [175]:
#print df.isnull().sum()

In [73]:
df.isnull().values.any()

True

In [74]:
print df.isnull().sum().sum()

5

In [143]:
#Question 7

In [242]:
from math import pi

import pandas as pd

from bokeh.io import output_file, show
from bokeh.palettes import Category20c
from bokeh.plotting import figure
from bokeh.transform import cumsum

In [144]:
#Question 8

In [201]:
#Csv3[Csv3["ThruTime.MF"]== "23:00"]

In [269]:
Csv3["ThruTime.MF"] = pd.to_datetime(Csv3["ThruTime.MF"])
#Csv3["ThruTime.MF"]

In [145]:
#Question 9

In [283]:
Csv3["LocationMilestones.LastRemodelDate"] = pd.to_datetime(Csv3["LocationMilestones.LastRemodelDate"])
Csv3["LocationMilestones.LastRemodelDate"]

0                     NaT
1                     NaT
2                     NaT
3     2013-06-27 12:00:00
4     2004-10-17 12:00:00
5     2013-10-10 12:00:00
6     2014-04-03 12:00:00
7                     NaT
8                     NaT
9                     NaT
10    2007-10-18 12:00:00
11                    NaT
12                    NaT
13                    NaT
14    2012-06-21 12:00:00
15                    NaT
16    2004-08-08 12:00:00
17                    NaT
18    2013-06-27 12:00:00
19                    NaT
20                    NaT
21                    NaT
22    2012-03-22 12:00:00
23    2012-03-22 12:00:00
24    2012-03-22 12:00:00
25                    NaT
26    2012-06-21 12:00:00
27    2012-06-21 12:00:00
28    2017-03-30 12:00:00
29    2012-06-21 12:00:00
              ...
85    2012-06-21 12:00:00
86    2014-04-03 12:00:00
87    2012-06-21 12:00:00
88    2012-06-21 12:00:00
89                    NaT
90    2017-04-13 12:00:00
91    2012-10-11 12:00:00
92    2010-10-14 12:00:00
93    2012-03-22 12:00:00
94    2012-06-21 12:00:00
95    2012-03-22 12:00:00
96    2018-04-13 12:00:00
97    2014-04-03 12:00:00
98    2006-05-12 12:00:00
99    2003-08-12 12:00:00
100   2012-03-22 12:00:00
101   2007-03-23 12:00:00
102   2012-10-11 12:00:00
103                   NaT
104   2012-06-21 12:00:00
105   2012-06-21 12:00:00
106   2012-06-21 12:00:00
107   2012-03-22 12:00:00
108   2011-06-02 12:00:00
109   2011-10-06 12:00:00
110                   NaT
111   2011-10-06 12:00:00
112                   NaT
113   2014-10-12 12:00:00
114                   NaT
Name: LocationMilestones.LastRemodelDate, Length: 115, dtype: datetime64[ns]

In [287]:
CF = Csv3[Csv3["LocationMilestones.LastRemodelDate"].notnull()]

In [292]:
CF.set_index("LocationMilestones.LastRemodelDate").to_dict()

{'Address.City_x': {Timestamp('2000-03-01 12:00:00'): 'Roswell',
  Timestamp('2003-08-12 12:00:00'): 'Mobile',
  Timestamp('2004-08-08 12:00:00'): 'Maryville',
  Timestamp('2004-09-19 12:00:00'): 'Marietta',
  Timestamp('2004-10-17 12:00:00'): 'Columbus',
  Timestamp('2006-05-12 12:00:00'): 'Aiken',
  Timestamp('2007-03-23 12:00:00'): 'Madison',
  Timestamp('2007-04-13 12:00:00'): 'Warner Robins',
  Timestamp('2007-07-13 12:00:00'): 'Florence',
  Timestamp('2007-10-18 12:00:00'): 'Fayetteville',
  Timestamp('2009-07-09 12:00:00'): 'Tallahassee',
  Timestamp('2010-10-14 12:00:00'): 'Nashville',
  Timestamp('2011-06-02 12:00:00'): 'Palm Desert',
  Timestamp('2011-10-06 12:00:00'): 'Apple Valley',
  Timestamp('2012-03-22 12:00:00'): 'Asheville',
  Timestamp('2012-06-21 12:00:00'): 'Spartanburg',
  Timestamp('2012-10-11 12:00:00'): 'Hendersonville',
  Timestamp('2013-03-21 12:00:00'): 'Atlanta',
  Timestamp('2013-06-27 12:00:00'): 'Mary Esther',
  Timestamp('2013-10-10 12:00:00'): 'Sandy Springs',
  Timestamp('2014-04-03 12:00:00'): 'Knoxville',
  Timestamp('2014-10-12 12:00:00'): 'Grand Junction',
  Timestamp('2017-03-30 12:00:00'): 'Gainesville',
  Timestamp('2017-04-13 12:00:00'): 'Knoxville',
  Timestamp('2017-10-26 12:00:00'): 'Tuscaloosa',
  Timestamp('2018-04-13 12:00:00'): 'Daphne'},
 'Address.City_y': {Timestamp('2000-03-01 12:00:00'): 'Roswell',
  Timestamp('2003-08-12 12:00:00'): 'Mobile',
  Timestamp('2004-08-08 12:00:00'): 'Maryville',
  Timestamp('2004-09-19 12:00:00'): 'Marietta',
  Timestamp('2004-10-17 12:00:00'): 'Columbus',
  Timestamp('2006-05-12 12:00:00'): 'Aiken',
  Timestamp('2007-03-23 12:00:00'): 'Madison',
  Timestamp('2007-04-13 12:00:00'): 'Warner Robins',
  Timestamp('2007-07-13 12:00:00'): 'Florence',
  Timestamp('2007-10-18 12:00:00'): 'Fayetteville',
  Timestamp('2009-07-09 12:00:00'): 'Tallahassee',
  Timestamp('2010-10-14 12:00:00'): 'Nashville',
  Timestamp('2011-06-02 12:00:00'): 'Jackson',
  Timestamp('2011-10-06 12:00:00'): 'Cordova',
  Timestamp('2012-03-22 12:00:00'): 'Asheville',
  Timestamp('2012-06-21 12:00:00'): 'Spartanburg',
  Timestamp('2012-10-11 12:00:00'): 'Hendersonville',
  Timestamp('2013-03-21 12:00:00'): 'Atlanta',
  Timestamp('2013-06-27 12:00:00'): 'Mary Esther',
  Timestamp('2013-10-10 12:00:00'): 'Sandy Springs',
  Timestamp('2014-04-03 12:00:00'): 'Knoxville',
  Timestamp('2014-10-12 12:00:00'): 'Memphis',
  Timestamp('2017-03-30 12:00:00'): 'Gainesville',
  Timestamp('2017-04-13 12:00:00'): 'Knoxville',
  Timestamp('2017-10-26 12:00:00'): 'Tuscaloosa',
  Timestamp('2018-04-13 12:00:00'): 'Daphne'},
 'BeginTime.MF': {Timestamp('2000-03-01 12:00:00'): '08:00:00',
  Timestamp('2003-08-12 12:00:00'): '08:00:00',
  Timestamp('2004-08-08 12:00:00'): '08:00:00',
  Timestamp('2004-09-19 12:00:00'): '08:00:00',
  Timestamp('2004-10-17 12:00:00'): '08:00:00',
  Timestamp('2006-05-12 12:00:00'): '08:00:00',
  Timestamp('2007-03-23 12:00:00'): '08:00:00',
  Timestamp('2007-04-13 12:00:00'): '08:00:00',
  Timestamp('2007-07-13 12:00:00'): '08:00:00',
  Timestamp('2007-10-18 12:00:00'): '08:00:00',
  Timestamp('2009-07-09 12:00:00'): '08:00:00',
  Timestamp('2010-10-14 12:00:00'): '08:00:00',
  Timestamp('2011-06-02 12:00:00'): '08:00:00',
  Timestamp('2011-10-06 12:00:00'): '08:00:00',
  Timestamp('2012-03-22 12:00:00'): '08:00:00',
  Timestamp('2012-06-21 12:00:00'): '08:00:00',
  Timestamp('2012-10-11 12:00:00'): '08:00:00',
  Timestamp('2013-03-21 12:00:00'): '08:00:00',
  Timestamp('2013-06-27 12:00:00'): '08:00:00',
  Timestamp('2013-10-10 12:00:00'): '08:00:00',
  Timestamp('2014-04-03 12:00:00'): '08:00:00',
  Timestamp('2014-10-12 12:00:00'): '08:00:00',
  Timestamp('2017-03-30 12:00:00'): '08:00:00',
  Timestamp('2017-04-13 12:00:00'): '08:00:00',
  Timestamp('2017-10-26 12:00:00'): '08:00:00',
  Timestamp('2018-04-13 12:00:00'): '08:00:00'},
 'FaxNumber': {Timestamp('2000-03-01 12:00:00'): '(470) 385-3922',
  Timestamp('2003-08-12 12:00:00'): '(251) 287-9863',
  Timestamp('2004-08-08 12:00:00'): '(865) 238-7098',
  Timestamp('2004-09-19 12:00:00'): '(770) 250-4905',
  Timestamp('2004-10-17 12:00:00'): '(706) 225-5604',
  Timestamp('2006-05-12 12:00:00'): '(803) 295-5701',
  Timestamp('2007-03-23 12:00:00'): '(615) 756-3261',
  Timestamp('2007-04-13 12:00:00'): '(478) 333-4037',
  Timestamp('2007-07-13 12:00:00'): '(256) 712-3239',
  Timestamp('2007-10-18 12:00:00'): '(678) 734-9930',
  Timestamp('2009-07-09 12:00:00'): '(850) 907-2703',
  Timestamp('2010-10-14 12:00:00'): '(615) 925-3840',
  Timestamp('2011-06-02 12:00:00'): '(731) 256-3707',
  Timestamp('2011-10-06 12:00:00'): '(901) 251-0368',
  Timestamp('2012-03-22 12:00:00'): '(828) 333-9991',
  Timestamp('2012-06-21 12:00:00'): '(864) 345-6000',
  Timestamp('2012-10-11 12:00:00'): '(615) 431-3581',
  Timestamp('2013-03-21 12:00:00'): '(404) 720-7734',
  Timestamp('2013-06-27 12:00:00'): '(850) 659-3286',
  Timestamp('2013-10-10 12:00:00'): '(678) 704-8130',
  Timestamp('2014-04-03 12:00:00'): '(865) 291-4757',
  Timestamp('2014-10-12 12:00:00'): '(901) 251-5411',
  Timestamp('2017-03-30 12:00:00'): '(678) 928-3709',
  Timestamp('2017-04-13 12:00:00'): nan,
  Timestamp('2017-10-26 12:00:00'): '(205) 535-3724',
  Timestamp('2018-04-13 12:00:00'): '(251) 287-9804'},
 'ID_x': {Timestamp('2000-03-01 12:00:00'): 1761L,
  Timestamp('2003-08-12 12:00:00'): 797L,
  Timestamp('2004-08-08 12:00:00'): 1250L,
  Timestamp('2004-09-19 12:00:00'): 1106L,
  Timestamp('2004-10-17 12:00:00'): 1179L,
  Timestamp('2006-05-12 12:00:00'): 1310L,
  Timestamp('2007-03-23 12:00:00'): 144L,
  Timestamp('2007-04-13 12:00:00'): 1380L,
  Timestamp('2007-07-13 12:00:00'): 1322L,
  Timestamp('2007-10-18 12:00:00'): 778L,
  Timestamp('2009-07-09 12:00:00'): 1973L,
  Timestamp('2010-10-14 12:00:00'): 1059L,
  Timestamp('2011-06-02 12:00:00'): 940L,
  Timestamp('2011-10-06 12:00:00'): 939L,
  Timestamp('2012-03-22 12:00:00'): 1807L,
  Timestamp('2012-06-21 12:00:00'): 1349L,
  Timestamp('2012-10-11 12:00:00'): 1511L,
  Timestamp('2013-03-21 12:00:00'): 1486L,
  Timestamp('2013-06-27 12:00:00'): 740L,
  Timestamp('2013-10-10 12:00:00'): 2333L,
  Timestamp('2014-04-03 12:00:00'): 2057L,
  Timestamp('2014-10-12 12:00:00'): 93L,
  Timestamp('2017-03-30 12:00:00'): 796L,
  Timestamp('2017-04-13 12:00:00'): 795L,
  Timestamp('2017-10-26 12:00:00'): 1787L,
  Timestamp('2018-04-13 12:00:00'): 1274L},
 'ID_y': {Timestamp('2000-03-01 12:00:00'): 1761L,
  Timestamp('2003-08-12 12:00:00'): 797L,
  Timestamp('2004-08-08 12:00:00'): 1250L,
  Timestamp('2004-09-19 12:00:00'): 1106L,
  Timestamp('2004-10-17 12:00:00'): 1179L,
  Timestamp('2006-05-12 12:00:00'): 1310L,
  Timestamp('2007-03-23 12:00:00'): 144L,
  Timestamp('2007-04-13 12:00:00'): 1380L,
  Timestamp('2007-07-13 12:00:00'): 1322L,
  Timestamp('2007-10-18 12:00:00'): 778L,
  Timestamp('2009-07-09 12:00:00'): 1973L,
  Timestamp('2010-10-14 12:00:00'): 1059L,
  Timestamp('2011-06-02 12:00:00'): 921L,
  Timestamp('2011-10-06 12:00:00'): 1844L,
  Timestamp('2012-03-22 12:00:00'): 1807L,
  Timestamp('2012-06-21 12:00:00'): 1349L,
  Timestamp('2012-10-11 12:00:00'): 1511L,
  Timestamp('2013-03-21 12:00:00'): 1486L,
  Timestamp('2013-06-27 12:00:00'): 740L,
  Timestamp('2013-10-10 12:00:00'): 2333L,
  Timestamp('2014-04-03 12:00:00'): 2057L,
  Timestamp('2014-10-12 12:00:00'): 1030L,
  Timestamp('2017-03-30 12:00:00'): 796L,
  Timestamp('2017-04-13 12:00:00'): 795L,
  Timestamp('2017-10-26 12:00:00'): 1787L,
  Timestamp('2018-04-13 12:00:00'): 1274L},
 'IsOpen.Sat': {Timestamp('2000-03-01 12:00:00'): True,
  Timestamp('2003-08-12 12:00:00'): True,
  Timestamp('2004-08-08 12:00:00'): True,
  Timestamp('2004-09-19 12:00:00'): True,
  Timestamp('2004-10-17 12:00:00'): True,
  Timestamp('2006-05-12 12:00:00'): True,
  Timestamp('2007-03-23 12:00:00'): True,
  Timestamp('2007-04-13 12:00:00'): True,
  Timestamp('2007-07-13 12:00:00'): True,
  Timestamp('2007-10-18 12:00:00'): True,
  Timestamp('2009-07-09 12:00:00'): True,
  Timestamp('2010-10-14 12:00:00'): True,
  Timestamp('2011-06-02 12:00:00'): False,
  Timestamp('2011-10-06 12:00:00'): True,
  Timestamp('2012-03-22 12:00:00'): True,
  Timestamp('2012-06-21 12:00:00'): True,
  Timestamp('2012-10-11 12:00:00'): True,
  Timestamp('2013-03-21 12:00:00'): True,
  Timestamp('2013-06-27 12:00:00'): True,
  Timestamp('2013-10-10 12:00:00'): True,
  Timestamp('2014-04-03 12:00:00'): True,
  Timestamp('2014-10-12 12:00:00'): True,
  Timestamp('2017-03-30 12:00:00'): True,
  Timestamp('2017-04-13 12:00:00'): True,
  Timestamp('2017-10-26 12:00:00'): True,
  Timestamp('2018-04-13 12:00:00'): True},
 'IsOpen.Sun': {Timestamp('2000-03-01 12:00:00'): True,
  Timestamp('2003-08-12 12:00:00'): True,
  Timestamp('2004-08-08 12:00:00'): False,
  Timestamp('2004-09-19 12:00:00'): True,
  Timestamp('2004-10-17 12:00:00'): True,
  Timestamp('2006-05-12 12:00:00'): True,
  Timestamp('2007-03-23 12:00:00'): True,
  Timestamp('2007-04-13 12:00:00'): False,
  Timestamp('2007-07-13 12:00:00'): True,
  Timestamp('2007-10-18 12:00:00'): True,
  Timestamp('2009-07-09 12:00:00'): True,
  Timestamp('2010-10-14 12:00:00'): False,
  Timestamp('2011-06-02 12:00:00'): True,
  Timestamp('2011-10-06 12:00:00'): False,
  Timestamp('2012-03-22 12:00:00'): True,
  Timestamp('2012-06-21 12:00:00'): True,
  Timestamp('2012-10-11 12:00:00'): True,
  Timestamp('2013-03-21 12:00:00'): False,
  Timestamp('2013-06-27 12:00:00'): True,
  Timestamp('2013-10-10 12:00:00'): True,
  Timestamp('2014-04-03 12:00:00'): True,
  Timestamp('2014-10-12 12:00:00'): False,
  Timestamp('2017-03-30 12:00:00'): False,
  Timestamp('2017-04-13 12:00:00'): True,
  Timestamp('2017-10-26 12:00:00'): True,
  Timestamp('2018-04-13 12:00:00'): True},
 'LocationMilestones.OpenDate': {Timestamp('2000-03-01 12:00:00'): '2000-03-01T12:00:00',
  Timestamp('2003-08-12 12:00:00'): '1996-07-24T12:00:00',
  Timestamp('2004-08-08 12:00:00'): '2000-03-01T12:00:00',
  Timestamp('2004-09-19 12:00:00'): '1997-10-08T12:00:00',
  Timestamp('2004-10-17 12:00:00'): '1999-03-03T12:00:00',
  Timestamp('2006-05-12 12:00:00'): '2000-10-04T12:00:00',
  Timestamp('2007-03-23 12:00:00'): '1981-02-24T12:00:00',
  Timestamp('2007-04-13 12:00:00'): '2001-10-10T12:00:00',
  Timestamp('2007-07-13 12:00:00'): '2001-03-07T12:00:00',
  Timestamp('2007-10-18 12:00:00'): '1995-10-04T12:00:00',
  Timestamp('2009-07-09 12:00:00'): '2005-07-20T12:00:00',
  Timestamp('2010-10-14 12:00:00'): '1997-03-05T12:00:00',
  Timestamp('2011-06-02 12:00:00'): '1995-03-08T12:00:00',
  Timestamp('2011-10-06 12:00:00'): '1994-10-05T12:00:00',
  Timestamp('2012-03-22 12:00:00'): '2003-07-23T12:00:00',
  Timestamp('2012-06-21 12:00:00'): '2001-07-25T12:00:00',
  Timestamp('2012-10-11 12:00:00'): '2003-03-05T12:00:00',
  Timestamp('2013-03-21 12:00:00'): '2002-10-09T12:00:00',
  Timestamp('2013-06-27 12:00:00'): '1995-10-04T12:00:00',
  Timestamp('2013-10-10 12:00:00'): '2008-10-08T12:00:00',
  Timestamp('2014-04-03 12:00:00'): '2006-07-19T12:00:00',
  Timestamp('2014-10-12 12:00:00'): '1980-10-28T12:00:00',
  Timestamp('2017-03-30 12:00:00'): '1997-07-23T12:00:00',
  Timestamp('2017-04-13 12:00:00'): '1996-03-06T12:00:00',
  Timestamp('2017-10-26 12:00:00'): '2002-03-06T12:00:00',
  Timestamp('2018-04-13 12:00:00'): '2000-07-19T12:00:00'},
 'Name_x': {Timestamp('2000-03-01 12:00:00'): 'Roswell',
  Timestamp('2003-08-12 12:00:00'): 'Bel-Air',
  Timestamp('2004-08-08 12:00:00'): 'Maryville',
  Timestamp('2004-09-19 12:00:00'): 'Cobb NE',
  Timestamp('2004-10-17 12:00:00'): 'Columbus',
  Timestamp('2006-05-12 12:00:00'): 'Aiken',
  Timestamp('2007-03-23 12:00:00'): 'Rivergate',
  Timestamp('2007-04-13 12:00:00'): 'Warner Robins',
  Timestamp('2007-07-13 12:00:00'): 'Florence',
  Timestamp('2007-10-18 12:00:00'): 'Fayetteville',
  Timestamp('2009-07-09 12:00:00'): 'Tallahassee North',
  Timestamp('2010-10-14 12:00:00'): 'Nashville East',
  Timestamp('2011-06-02 12:00:00'): 'Palm Desert',
  Timestamp('2011-10-06 12:00:00'): 'Apple Valley',
  Timestamp('2012-03-22 12:00:00'): 'Asheville',
  Timestamp('2012-06-21 12:00:00'): 'Spartanburg',
  Timestamp('2012-10-11 12:00:00'): 'Hendersonville',
  Timestamp('2013-03-21 12:00:00'): 'North Druid Hills',
  Timestamp('2013-06-27 12:00:00'): 'Mary Esther',
  Timestamp('2013-10-10 12:00:00'): 'Sandy Springs Prado',
  Timestamp('2014-04-03 12:00:00'): 'Knoxville North',
  Timestamp('2014-10-12 12:00:00'): 'Grand Junction',
  Timestamp('2017-03-30 12:00:00'): 'Gainesville',
  Timestamp('2017-04-13 12:00:00'): 'Knoxville NW',
  Timestamp('2017-10-26 12:00:00'): 'Tuscaloosa',
  Timestamp('2018-04-13 12:00:00'): 'Daphne'},
 'Name_y': {Timestamp('2000-03-01 12:00:00'): 'Roswell',
  Timestamp('2003-08-12 12:00:00'): 'Bel-Air',
  Timestamp('2004-08-08 12:00:00'): 'Maryville',
  Timestamp('2004-09-19 12:00:00'): 'Cobb NE',
  Timestamp('2004-10-17 12:00:00'): 'Columbus',
  Timestamp('2006-05-12 12:00:00'): 'Aiken',
  Timestamp('2007-03-23 12:00:00'): 'Rivergate',
  Timestamp('2007-04-13 12:00:00'): 'Warner Robins',
  Timestamp('2007-07-13 12:00:00'): 'Florence',
  Timestamp('2007-10-18 12:00:00'): 'Fayetteville',
  Timestamp('2009-07-09 12:00:00'): 'Tallahassee North',
  Timestamp('2010-10-14 12:00:00'): 'Nashville East',
  Timestamp('2011-06-02 12:00:00'): 'Jackson',
  Timestamp('2011-10-06 12:00:00'): 'Cordova',
  Timestamp('2012-03-22 12:00:00'): 'Asheville',
  Timestamp('2012-06-21 12:00:00'): 'Spartanburg',
  Timestamp('2012-10-11 12:00:00'): 'Hendersonville',
  Timestamp('2013-03-21 12:00:00'): 'North Druid Hills',
  Timestamp('2013-06-27 12:00:00'): 'Mary Esther',
  Timestamp('2013-10-10 12:00:00'): 'Sandy Springs Prado',
  Timestamp('2014-04-03 12:00:00'): 'Knoxville North',
  Timestamp('2014-10-12 12:00:00'): 'Memphis NE',
  Timestamp('2017-03-30 12:00:00'): 'Gainesville',
  Timestamp('2017-04-13 12:00:00'): 'Knoxville NW',
  Timestamp('2017-10-26 12:00:00'): 'Tuscaloosa',
  Timestamp('2018-04-13 12:00:00'): 'Daphne'},
 'PhoneNumber': {Timestamp('2000-03-01 12:00:00'): '(770) 998-0144',
  Timestamp('2003-08-12 12:00:00'): '(251) 471-9760',
  Timestamp('2004-08-08 12:00:00'): '(865) 982-1590',
  Timestamp('2004-09-19 12:00:00'): '(770) 321-8545',
  Timestamp('2004-10-17 12:00:00'): '(706) 321-0831',
  Timestamp('2006-05-12 12:00:00'): '(803) 644-2721',
  Timestamp('2007-03-23 12:00:00'): '(615) 859-5260',
  Timestamp('2007-04-13 12:00:00'): '(478) 971-2141',
  Timestamp('2007-07-13 12:00:00'): '(256) 764-6924',
  Timestamp('2007-10-18 12:00:00'): '(770) 719-9766',
  Timestamp('2009-07-09 12:00:00'): '(850) 894-3213',
  Timestamp('2010-10-14 12:00:00'): '(615) 889-4734',
  Timestamp('2011-06-02 12:00:00'): '(760) 341-9307',
  Timestamp('2011-10-06 12:00:00'): '(760) 247-4111',
  Timestamp('2012-03-22 12:00:00'): '(828) 298-1262',
  Timestamp('2012-06-21 12:00:00'): '(864) 574-1211',
  Timestamp('2012-10-11 12:00:00'): '(615) 826-6895',
  Timestamp('2013-03-21 12:00:00'): '(404) 267-0060',
  Timestamp('2013-06-27 12:00:00'): '(850) 243-4188',
  Timestamp('2013-10-10 12:00:00'): '(678) 704-8120',
  Timestamp('2014-04-03 12:00:00'): '(865) 291-0086',
  Timestamp('2014-10-12 12:00:00'): '(970) 245-8056',
  Timestamp('2017-03-30 12:00:00'): '(770) 532-6670',
  Timestamp('2017-04-13 12:00:00'): '(865) 947-7636',
  Timestamp('2017-10-26 12:00:00'): '(205) 462-1064',
  Timestamp('2018-04-13 12:00:00'): '(251) 621-3540'},
 'Store.StoreDistrictID': {Timestamp('2000-03-01 12:00:00'): 334L,
  Timestamp('2003-08-12 12:00:00'): 359L,
  Timestamp('2004-08-08 12:00:00'): 351L,
  Timestamp('2004-09-19 12:00:00'): 334L,
  Timestamp('2004-10-17 12:00:00'): 340L,
  Timestamp('2006-05-12 12:00:00'): 337L,
  Timestamp('2007-03-23 12:00:00'): 333L,
  Timestamp('2007-04-13 12:00:00'): 346L,
  Timestamp('2007-07-13 12:00:00'): 369L,
  Timestamp('2007-10-18 12:00:00'): 336L,
  Timestamp('2009-07-09 12:00:00'): 348L,
  Timestamp('2010-10-14 12:00:00'): 333L,
  Timestamp('2011-06-02 12:00:00'): 205L,
  Timestamp('2011-10-06 12:00:00'): 248L,
  Timestamp('2012-03-22 12:00:00'): 362L,
  Timestamp('2012-06-21 12:00:00'): 337L,
  Timestamp('2012-10-11 12:00:00'): 333L,
  Timestamp('2013-03-21 12:00:00'): 335L,
  Timestamp('2013-06-27 12:00:00'): 348L,
  Timestamp('2013-10-10 12:00:00'): 335L,
  Timestamp('2014-04-03 12:00:00'): 351L,
  Timestamp('2014-10-12 12:00:00'): 179L,
  Timestamp('2017-03-30 12:00:00'): 335L,
  Timestamp('2017-04-13 12:00:00'): 351L,
  Timestamp('2017-10-26 12:00:00'): 340L,
  Timestamp('2018-04-13 12:00:00'): 359L},
 'ThruTime.MF': {Timestamp('2000-03-01 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2003-08-12 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2004-08-08 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2004-09-19 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2004-10-17 12:00:00'): Timestamp('2019-07-26 23:00:00'),
  Timestamp('2006-05-12 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2007-03-23 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2007-04-13 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2007-07-13 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2007-10-18 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2009-07-09 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2010-10-14 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2011-06-02 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2011-10-06 12:00:00'): Timestamp('2019-07-26 23:00:00'),
  Timestamp('2012-03-22 12:00:00'): Timestamp('2019-07-26 23:00:00'),
  Timestamp('2012-06-21 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2012-10-11 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2013-03-21 12:00:00'): Timestamp('2019-07-26 23:00:00'),
  Timestamp('2013-06-27 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2013-10-10 12:00:00'): Timestamp('2019-07-26 23:00:00'),
  Timestamp('2014-04-03 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2014-10-12 12:00:00'): Timestamp('2019-07-26 23:00:00'),
  Timestamp('2017-03-30 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2017-04-13 12:00:00'): Timestamp('2019-07-26 22:00:00'),
  Timestamp('2017-10-26 12:00:00'): Timestamp('2019-07-26 00:00:00'),
  Timestamp('2018-04-13 12:00:00'): Timestamp('2019-07-26 22:00:00')},
 'TimeZone.TimeZoneCode': {Timestamp('2000-03-01 12:00:00'): 'EST',
  Timestamp('2003-08-12 12:00:00'): 'CST',
  Timestamp('2004-08-08 12:00:00'): 'EST',
  Timestamp('2004-09-19 12:00:00'): 'EST',
  Timestamp('2004-10-17 12:00:00'): 'EST',
  Timestamp('2006-05-12 12:00:00'): 'EST',
  Timestamp('2007-03-23 12:00:00'): 'CST',
  Timestamp('2007-04-13 12:00:00'): 'EST',
  Timestamp('2007-07-13 12:00:00'): 'CST',
  Timestamp('2007-10-18 12:00:00'): 'EST',
  Timestamp('2009-07-09 12:00:00'): 'EST',
  Timestamp('2010-10-14 12:00:00'): 'CST',
  Timestamp('2011-06-02 12:00:00'): 'PST',
  Timestamp('2011-10-06 12:00:00'): 'PST',
  Timestamp('2012-03-22 12:00:00'): 'EST',
  Timestamp('2012-06-21 12:00:00'): 'EST',
  Timestamp('2012-10-11 12:00:00'): 'CST',
  Timestamp('2013-03-21 12:00:00'): 'EST',
  Timestamp('2013-06-27 12:00:00'): 'CST',
  Timestamp('2013-10-10 12:00:00'): 'EST',
  Timestamp('2014-04-03 12:00:00'): 'EST',
  Timestamp('2014-10-12 12:00:00'): 'MST',
  Timestamp('2017-03-30 12:00:00'): 'EST',
  Timestamp('2017-04-13 12:00:00'): 'EST',
  Timestamp('2017-10-26 12:00:00'): 'CST',
  Timestamp('2018-04-13 12:00:00'): 'CST'}}

In [221]:
#Question 10

In [217]:
gk1 = Csv(3.groupby("Address.City_x"))
gk2 = Csv3.groupby("Address.City_y")

In [179]:
gk1.first()
gk1.get_group("Alabaster")

In [197]:
#gk1.size()
#gk2.size()

In [142]:
#Question 11

In [235]:
TIME = pd.date_range(start = "1980-10-27", end = "2007-03-07", freq = "A")
TIME

DatetimeIndex(['1980-12-31', '1981-12-31', '1982-12-31', '1983-12-31',
               '1984-12-31', '1985-12-31', '1986-12-31', '1987-12-31',
               '1988-12-31', '1989-12-31', '1990-12-31', '1991-12-31',
               '1992-12-31', '1993-12-31', '1994-12-31', '1995-12-31',
               '1996-12-31', '1997-12-31', '1998-12-31', '1999-12-31',
               '2000-12-31', '2001-12-31', '2002-12-31', '2003-12-31',
               '2004-12-31', '2005-12-31', '2006-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')

In [233]:
type(TIME)

pandas.core.indexes.datetimes.DatetimeIndex

In [238]:
s = pd.Series(TIME)
s.head(3)

0   1980-12-31
1   1981-12-31
2   1982-12-31
dtype: datetime64[ns]